{% set version = "1.4.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-futile.logger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/futile.logger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/futile.logger/futile.logger_{{ version }}.tar.gz
  sha256: 5e8b32d65f77a86d17d90fd8690fc085aa0612df8018e4d6d6c1a60fa65776e4

build:
  number: 1006
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-futile.options
    - r-lambda.r >=1.1.0
  run:
    - r-base
    - r-futile.options
    - r-lambda.r >=1.1.0

test:
  commands:
    - $R -e "library('futile.logger')"           # [not win]
    - "\"%R%\" -e \"library('futile.logger')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=futile.logger
  license: LGPL-3.0-only
  summary: Provides a simple yet powerful logging utility. Based loosely on log4j, futile.logger takes advantage of R idioms to make logging a convenient and easy to use replacement for cat and print statements.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
