appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: c2R65k4v3jE15BxMRRonP9TFU+Kwt/3bJvQl/Y3+e30LwI/KODL9hpu0JbSoMILkXkbrBWht6dMpkDLM77wSkC0D0GilOsyGAv9dBclc84p14AFFY4JPWC8ckhgDqS6eEjn4shYkzXeTuR55aadBRQy6SaOMNcJfQaK1YiN3qso3nylOkdmusMT8QfdY7wa2iJx3KHdee148e2u4JiKlUTtGY60oSe4lDO7aLL1AB0VrDVD54sHf9Cp7zzK8GWFPb+1KO7pFyiTOAj3OjxrXrwLVJKslimTzjRLtG4sauPx+1IT4q1Me6IMYLrohbPL73I1Q7gwn2O3lURoC+0UrsT+5beq9EuXXeD1jlF53f4liluJyoa7im5r/SSmDzPaCyJ4QbVE9wJ7k/OtQ9giweprMePTDCKhYbpnMxNVh/Hz60LhVjxIY7Fo7N24OqUjlfPpbIjL0J01rCrZX6v03z8dYly/svFhCV+KK7tY0kMWGfpnjPK9+ooI+VnCDoTU0W9aLBVowsvsH1RHUqIhhyYwkxHbeCeu8flW/Rlzt/EB5K1aHeaz9zI95tyq7lTD8XTHaIRdt2SZNKw+uVjxyeU8Ax/77yMhSu00Jv33jaoUkqONruFlysQD3j6U72lWG72waA6RBKKVA6mAz0o+de5XinNCLi8QBhakPo4vHqJU=
conda_forge_output_validation: true
