travis:
  secure:
    BINSTAR_TOKEN: g+aTnMqSp+dguQxdpQ1/Tq9Vjg67N+FhN4DYPjZvb4OOL0uUk2j4HNlZbO26cbt/ed7aU5oPiC864DVokbGS7sOLUsYs7Q+gsVAqpJxIx/TbmNrH4tw94M/QXm5k6fOlSv1MztDZ3Gru1lSy+pD2ybZrzfKK04Yb7YLSDzLEDhXf2YcWlLNKVWBoknRg8k3Ea8xBf+n96tygFidzsuisL3rsf53R++TGtGZsIAZ5ujtDrmhsMhTfv3xC2zm0bC8Ahgcw4dem/rWBRafhxfykJPAcjPMibP2RqQbdV2UG6UYJuc47zg4zNb0kFmw3lF03dv8rpC3tJC7FIKMTf9lppS1gYtRNM+5iq2EmyLfgmHUcawAhyp/v7UdBNg3tyrj/pp44OS+82lC3FcqsBCTfTzRVJqkaBbpwtT9iDNOBQuIdRz8WceYXdChjlrLjNA56PnuuqHiZHbHaKG/5vxrtwZ8XZvKlERtNDJYJJiOUKonJFS63GrbFHNzyEdc5YkDn4JH2pEcTK+LEsLMgndxRlynfaiIuXeEdhAcnH6CPtf2lVPoVbFMPwQbk5YJnogUCUSLdbycunmZl7CZxDNYl+eCKMCvnYC+bwXp7O7pkmjWbl13MbrJhPGk7qevYgZrbNAjfyueFuhq7kU+pbou7vSpuxrMN47UMcuGGtVHHsoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
