travis:
  secure:
    BINSTAR_TOKEN: KjmioBT2PU/ALGY4AqklmzPn+iuIfaOeglC5LXsLemlh7OKhx3oSnq4DDKdkCdpRKy9eT0GzADMdfJH8f/2LkmBLkBmyQQ8m4VFUgr9JeF1y1eJqboFDXpLcjBSdInZsbAGwJ056QHYwM5v+sLau/Au6PDV8kZOYqlrW4ubitf8l0/Qg+eLEwxNXmGMxy02K1VwG4be+QmAUpgZ/f00i0BKmdSU4ckOno7J3SW1SUtHTNqnUVpAnLpyn3GcOvArWAcILjek9JH/aBgnco5uB5V0ZyabHZKQn43Q0C6KjqtS7FuQSZnyx/GafQIgBbqWRpf/qze6B30Y01Abi+GNktVhaP8nkoOfLd4nCBG6tIZ4BOska/TH/dNrIOGLR33qGz7oczYlUfKsFJQQ43ckc7A6DgAw0IWHMVVT34WlDP7lmpe/dDPMp2nygG9nVWiPL1iwTtrXI21QNoz1wD27r7NmkTR25gozcfvsJvxpkv1Ch78UBNtNy29+JfyMr1k94KnGm4d6dblXFy2RMYZ7W0r0SoI6vLeW8EN4cIOkpOubdtWj1hLTIslUg29YtXVD0OHZtpzQDZjotjexOlgf3YuOXaoFaRvir6QPO4Nl01G1l4b52bYRg8/DP4lqxmozk9iHO5mvfvKMx98GEilHOUuddABXzgYw+QpaHFeq2ylI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
