travis:
  secure:
    BINSTAR_TOKEN: upunNw+i8r5B6U94Gh5AFl/qch+4Ll9AHacPr0TplaJsm4qtwa5TMNu3ga4dR+YFlo0pxiV/w0Ci8D/HHqLOBxKFvF+toV5rgKt4QHwEoNj1tcELCUVHvVV3g/HCo74y0Qz3AwEBZwDiY6yYv9YPfQKNYHvmarTTH6ZSDhk050hmOu+/u7Rt+pimDqmzHkjv81Wk8zc9WdKj3KDEq+ccjp8M0UO2zjHaNSsuX8staf2SPP79ZlVaV+hZOjfJEnzmEvmptG5yi0uS1LgVh0JdbHNNcrZl557/tY8XSSU3sAQ0cvJAfe+dmkVUnz8s2XdVrlwCcPyzCW+CvzO9eDL0G4BawB9bR2czGDWcADkCVsLIqL4drKF39OgwQp45SuFnJLYtxDmGxvv5Kx+XLS944v/yvYFoyf0JzByA4i5jKRO+7JoDK14QiF17TxSVptcvKhbe9ypycMt0CyCOQ6VVPT62149Bbsoz9VEXuPEQ+RWxzFMbw32w7Yc8yxozSXSDZyWebyd1dU3bC2KFggu++fOWZh9LsTXrJNiJ/62NK9NHmcv/uT/ZvCmgj32hZk26fGjQnXbwWVYGkcHL23Caf1eJaxm5fZipq43mvSGQQGnc6tV86Upf+NsX98s0wLQzpdPx/riinNm61tUyjMQhM9v+s7zOOeXIlSwPl32IhYk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
