travis:
  secure:
    BINSTAR_TOKEN: aQz+pZcX9fLVgXGbRhR0EGbPkYnvTcWFSRqXl2M2Qw/DNyjKlYRQldK70+cFR1hc04OV3+NiK5ne2iHrnUzE3GYF+HDYz9Ja6u7O/GJLHGJ6guGFyl9gNMWtFCGMIOiykJPOEmMU9Ipm4OgCEMM+K6VFxHeLJdk9XyvlE2ZwMWRfF5JXLaKZRWMbN2v0fNUo12pPPt97pYybz6XD00+VoPDQa6nfOBwhVTKNVZs55iaPBmDB/HwaJz1qSl3b2cWbnGxIIaAuzhwiQsL/086m+N5Ox8Zw7lO6JlCPGKHOcDh3wN5HMzAiTA7zc51Jvo9NWNKFxoWP9v1z2ySRw9Rz6kfFxFtk8vTOaplcXI1uH1AtTFz6hZkeWGkriWPP8A1X2vGFO3R1756W8Z2VRK/nC1PsmgZIQ8JTk4WqwaZ7XU1DacW7tEUuIJmSEpUYzTz7PFJwGBtPcdOsjz2KfPNAaG49c7qWkrY7GwsPNLOUzasGUUTpAGE//ZVMGoBZdhE+XQN3dZOoirOPAQ7L/jrZ+kSJsWUAkf8AmgAXqFS9EROF/jl5ZqegeWfxVtD230g9XEA+odJM2W8tJUx64lzIdBXI6WSP5B5ipIXRA/Ao01m0XhY18X4qEt3OZ1Xyv8vimlRJmnHnifFvQBmIjJ3igcBzFyhbGBZdhM38v9uTXZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
