travis:
  secure:
    BINSTAR_TOKEN: D+79K9Ly7r6MMQ2QzDmXmfJIaq8T8+YA8UCFE33r+8FWRdiAbHvAAZ5cEzc/9qgFaRaSqs7ec2FMuayHFps1XydTM+pWPp6ghTDYF6ZnEmaFDyP2zhxuAGiOsHIpY61piup3j3f7eLNykBx18xHA3ntRsGdo2+CRCRg8wtx2wsW+kIHhgAvj9JTudkAMb01ifnBpuG8fc3BROGScYqfvxGPu6XRz3Uj5I+WznOShw0bkb20V9OzGWn0lppDpJaaMMdhCd0gybqVSDyhrCvz9Wze1Uh15379y/6PCdbDwo8SKmjtCDRqDX8Oaufab1jscL8iWQAxu3O7Ls+CFBnx/s9JN3MwvbVV2w8zD3y+c+2SwqQI+WlBXz/az0CS9IHcuD3HbpRWO6nZ5mbG0bJNtZeprIZ9n46CjgYLIGeTbE5UEtbGhk7xuw+pTBVj/6ni5GPq35u2zmMdmXlfBO/t5bvfRTyzeRAMcVDrZKwWzY1QR9pS7bY98wYXOyOSrinAwo8VnmxLvUjh7g43ADN5y809MNXxgayY/0HqKjFczb0Dfly11S0KLsvy51DQaOXWnWXOYr5tQ+CKvJ4ODlryX/ZqvpOEv2mREaRpHwpGM0w5Ia5EicIHwn4bZAKGE7r863mMXpGhFkhJn76c4+0enF1ryCPbA2XZLmWlCGZvhH7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
